version: '1.0.0'

services:
  client:
    container_name: client
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - 2025:80

  server:
    container_name: server
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - 2031:2031
    volumes:
      - ./server/src/:/app/src/
