services:
  client:
    container_name: client
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - 5001:80

  server:
    container_name: server
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - 5002:3000
    volumes:
      - ./server/src/:/app/src/
